insert into resource (icon, item_id, name, unique_name)
values ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_dreamingglory.jpg', 22786, 'DreamingGlory',
        'dreaming-glory'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_nightmarevine.jpg', 22792, 'NightmareVine',
        'nightmare-vine'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_manathistle.jpg', 22793, 'ManaThistle',
        'mana-thistle'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_nightmareseed.jpg', 22797, 'NightmareSeed',
        'nightmare-seed'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_netherbloom.jpg',22791,'Netherbloom','netherbloom'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_fellotus.jpg', 22794, 'FelLotus', 'fel-lotus'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_ore_feliron.jpg', 23424, 'FelIronOre', 'fel-iron-ore'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_ore_eternium.jpg', 23427, 'EterniumOre', 'eternium-ore'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_ore_adamantium.jpg', 23425, 'AdamantiteOre',
        'adamantite-ore'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_ore_khorium.jpg', 23426, 'KhoriumOre', 'khorium-ore'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_bloodgem_03.jpg', 23077, 'BloodGarnet',
        'blood-garnet'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_flamespessarite_03.jpg', 21929, 'FlameSpessarite',
        'flame-spessarite'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_goldendraenite_03.jpg', 23112, 'GoldenDraenite',
        'golden-draenite'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_ebondraenite_03.jpg', 23107, 'ShadowDraenite',
        'shadow-draenite'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_deepperidot_03.jpg', 23079, 'DeepPeridot',
        'deep-peridot'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_azuredraenite_03.jpg', 23117, 'AzureMoonstone',
        'azure-moonstone'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_jewelcrafting_dawnstone_02.jpg', 23440, 'Dawnstone',
        'dawnstone'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_jewelcrafting_nightseye_02.jpg', 23441, 'Nightseye',
        'nightseye'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_jewelcrafting_starofelune_02.jpg', 23438, 'StarofElune',
        'star-of-elune'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_jewelcrafting_talasite_02.jpg', 23437, 'Talasite',
        'talasite'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_jewelcrafting_livingruby_02.jpg', 23436, 'LivingRuby',
        'living-ruby'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_jewelcrafting_nobletopaz_02.jpg', 23439, 'NobleTopaz',
        'noble-topaz'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_elemental_primal_mana.jpg', 22457, 'PrimalMana',
        'primal-mana'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_elemental_primal_fire.jpg', 21884, 'PrimalFire',
        'primal-fire'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_elemental_primal_life.jpg', 21886, 'PrimalLife',
        'primal-life'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_elemental_primal_earth.jpg', 22452, 'PrimalEarth',
        'primal-earth'),
       ('https://wow.zamimg.com/images/wow/icons/large/inv_elemental_primal_air.jpg', 22451, 'PrimalAir',
        'primal-air');

insert into server (server_fraction)
values ('gehennas-alliance'),
       ('gehennas-horde')