# insert into resource (id, icon, item_id, name, unique_name)
# values (1, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_dreamingglory.jpg', 22786, 'DreamingGlory',
#         'dreaming-glory'),
#        (2, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_nightmarevine.jpg', 22792, 'NightmareVine',
#         'nightmare-vine'),
#        (3, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_manathistle.jpg', 22793, 'ManaThistle',
#         'mana-thistle'),
#        (4, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_nightmareseed.jpg', 22797, 'NightmareSeed',
#         'nightmare-seed'),
#        (5, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_netherbloom.jpg', 22791, 'Netherbloom',
#         'netherbloom'),
#        (6, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_terrocone.jpg', 22789, 'Terocone', 'terocone'),
#        (7, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_fellotus.jpg', 22794, 'FelLotus', 'fel-lotus'),
#        (8, 'https://wow.zamimg.com/images/wow/icons/large/inv_ore_feliron.jpg', 23424, 'FelIronOre', 'fel-iron-ore'),
#        (9, 'https://wow.zamimg.com/images/wow/icons/large/inv_ore_eternium.jpg', 23427, 'EterniumOre', 'eternium-ore'),
#        (10, 'https://wow.zamimg.com/images/wow/icons/large/inv_ore_adamantium.jpg', 23425, 'AdamantiteOre',
#         'adamantite-ore'),
#        (11, 'https://wow.zamimg.com/images/wow/icons/large/inv_ore_khorium.jpg', 23426, 'KhoriumOre', 'khorium-ore'),
#        (12, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_bloodgem_03.jpg', 23077, 'BloodGarnet',
#         'blood-garnet'),
#        (13, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_flamespessarite_03.jpg', 21929,
#         'FlameSpessarite',
#         'flame-spessarite'),
#        (14, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_goldendraenite_03.jpg', 23112, 'GoldenDraenite',
#         'golden-draenite'),
#        (15, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_ebondraenite_03.jpg', 23107, 'ShadowDraenite',
#         'shadow-draenite'),
#        (16, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_deepperidot_03.jpg', 23079, 'DeepPeridot',
#         'deep-peridot'),
#        (17, 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_azuredraenite_03.jpg', 23117, 'AzureMoonstone',
#         'azure-moonstone'),
#        (18, 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelcrafting_dawnstone_02.jpg', 23440, 'Dawnstone',
#         'dawnstone'),
#        (19, 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelcrafting_nightseye_02.jpg', 23441, 'Nightseye',
#         'nightseye'),
#        (20, 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelcrafting_starofelune_02.jpg', 23438, 'StarofElune',
#         'star-of-elune'),
#        (21, 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelcrafting_talasite_02.jpg', 23437, 'Talasite',
#         'talasite'),
#        (22, 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelcrafting_livingruby_02.jpg', 23436, 'LivingRuby',
#         'living-ruby'),
#        (23, 'https://wow.zamimg.com/images/wow/icons/large/in_jewelcrafting_nobletopaz_02.jpg', 23439, 'NobleTopaz',
#         'noble-topaz'),
#        (24, 'https://wow.zamimg.com/images/wow/icons/large/inv_elemental_primal_mana.jpg', 22457, 'PrimalMana',
#         'primal-mana'),
#        (25, 'https://wow.zamimg.com/images/wow/icons/large/inv_elemental_primal_fire.jpg', 21884, 'PrimalFire',
#         'primal-fire'),
#        (26, 'https://wow.zamimg.com/images/wow/icons/large/inv_elemental_primal_life.jpg', 21886, 'PrimalLife',
#         'primal-life'),
#        (27, 'https://wow.zamimg.com/images/wow/icons/large/inv_elemental_primal_earth.jpg', 22452, 'PrimalEarth',
#         'primal-earth'),
#        (28, 'https://wow.zamimg.com/images/wow/icons/large/inv_elemental_primal_air.jpg', 22451, 'PrimalAir',
#         'primal-air');
#
# insert into server (id, server_fraction)
# values (1, 'gehennas-alliance'),
#        (2, 'gehennas-horde')