create table if not exists employee
(
    id              bigint generated by default as identity
        constraint employee_pkey
            primary key,
    discord_name    varchar(255)
        constraint uk_o713vnu3h8p41rw7bjybtqbm
            unique,
    gold            bigint,
    server_fraction varchar(255)
);

alter table employee
    owner to postgres;

create table if not exists for_sale
(
    id               bigint generated by default as identity
        constraint for_sale_pkey
            primary key,
    adamantite_ore   integer,
    azure_moonstone  integer,
    blood_garnet     integer,
    date             date,
    dawnstone        integer,
    deep_peridot     integer,
    dreaming_glory   integer,
    eternium_ore     integer,
    fel_iron_ore     integer,
    fel_lotus        integer,
    flame_spessarite integer,
    golden_draenite  integer,
    living_ruby      integer,
    mana_thistle     integer,
    nightmare_seed   integer,
    nightmare_vine   integer,
    nightseye        integer,
    noble_topaz      integer,
    price            bigint,
    primal_air       integer,
    primal_earth     integer,
    primal_fire      integer,
    primal_life      integer,
    primal_mana      integer,
    shadow_draenite  integer,
    star_of_elune    integer,
    talasite         integer,
    employee_id      bigint
        constraint fkeifkwgr7qi4q8r31voqrgfrww
            references employee
);

alter table for_sale
    owner to postgres;

create table if not exists employee_for_sale_list
(
    employee_id      bigint not null
        constraint fk1eapieostwykhcp37pwv0cvm1
            references employee,
    for_sale_list_id bigint not null
        constraint uk_j8hrio0wmkmr334pq3ed7gqlh
            unique
        constraint fkhs1kif3om7yf9769hlpig7okk
            references for_sale
);

alter table employee_for_sale_list
    owner to postgres;

create table if not exists resource
(
    id          bigint generated by default as identity
        constraint resource_pkey
            primary key,
    icon        varchar(255),
    item_id     bigint,
    name        varchar(255),
    unique_name varchar(255)
);

alter table resource
    owner to postgres;

create table if not exists server
(
    id              bigint generated by default as identity
        constraint server_pkey
            primary key,
    server_fraction varchar(255)
);

alter table server
    owner to postgres;

create table if not exists resource_price
(
    id                 bigint generated by default as identity
        constraint resource_price_pkey
            primary key,
    price              bigint,
    scanned_on         timestamp,
    resource_id        bigint
        constraint fkfae49bhrh8n5yjtsgu6i74t3l
            references resource,
    server_fraction_id bigint
        constraint fktrqqo8jvwmic008uo3hd6oulk
            references server
);

alter table resource_price
    owner to postgres;

