create table if not exists resource
(
    id          bigint generated by default as identity
        constraint resource_pkey
            primary key,
    icon        varchar(255),
    item_id     bigint,
    name        varchar(255),
    unique_name varchar(255)
);

alter table resource
    owner to postgres;

create table if not exists server
(
    id              bigint generated by default as identity
        constraint server_pkey
            primary key,
    server_fraction varchar(255)
);

alter table server
    owner to postgres;

create table if not exists employee
(
    id           bigint generated by default as identity
        constraint employee_pkey
            primary key,
    discord_name varchar(255)
        constraint uk_o713vnu3h8p41rw7bjybtqbm
            unique,
    gold         bigint,
    server_id    bigint
        constraint fktkbe1prv4vo6xdlpl7sgw35ne
            references server
);

alter table employee
    owner to postgres;

create table if not exists for_sale
(
    id               bigint generated by default as identity
        constraint for_sale_pkey
            primary key,
    adamantite_ore   integer,
    azure_moonstone  integer,
    blood_garnet     integer,
    date             date,
    dawnstone        integer,
    deep_peridot     integer,
    dreaming_glory   integer,
    eternium_ore     integer,
    fel_iron_ore     integer,
    fel_lotus        integer,
    flame_spessarite integer,
    golden_draenite  integer,
    khorium_ore      integer,
    living_ruby      integer,
    mana_thistle     integer,
    netherbloom      integer,
    nightmare_seed   integer,
    nightmare_vine   integer,
    nightseye        integer,
    noble_topaz      integer,
    price            bigint,
    primal_air       integer,
    primal_earth     integer,
    primal_fire      integer,
    primal_life      integer,
    primal_mana      integer,
    shadow_draenite  integer,
    star_of_elune    integer,
    talasite         integer,
    terocone         integer,
    employee_id      bigint
        constraint fkeifkwgr7qi4q8r31voqrgfrww
            references employee
);

alter table for_sale
    owner to postgres;

create table if not exists resource_price
(
    id          bigint generated by default as identity
        constraint resource_price_pkey
            primary key,
    price       bigint,
    scanned_on  timestamp,
    resource_id bigint
        constraint fkfae49bhrh8n5yjtsgu6i74t3l
            references resource,
    server_id   bigint
        constraint fk531yudr7vqdp2qx4shh463x9p
            references server
);

alter table resource_price
    owner to postgres;

